nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-berry.cjs

packageExtensions:
  "@babel/eslint-parser@*":
    dependencies:
      "@babel/core": "*"
  "eslint-webpack-plugin@*":
    dependencies:
      "webpack": "*"