nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.1.0.cjs

packageExtensions:
  "@babel/eslint-parser@*":
    dependencies:
      "@babel/core": "*"
  "eslint-webpack-plugin@*":
    dependencies:
      "webpack": "*"